version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 2
    rebase-strategy: auto
    schedule:
      interval: weekly
      day: sunday
      time: "05:00"
      timezone: "Asia/Calcutta"
    labels:
      - "CI/CD"
    commit-message:
      prefix: ci

  - package-ecosystem: maven
    directory: /
    open-pull-requests-limit: 2
    rebase-strategy: auto
    schedule:
      interval: weekly
      day: sunday
      time: "05:00"
      timezone: "Asia/Calcutta"
